### ISSUE TITLE
(biolinkml) gen-owl not working for nmdc.yaml

### ISSUE THREAD

**Issue by wdduncan** [microbiomedata/nmdc-metadata#137]
Running `gen-owl` is failing with `nmdc.yaml` as input.
Here is my output log for a simple command `gen-owl schema/nmdc.yaml > temp.owl`:
```
gen-owl schema/nmdc.yaml > temp.owl
WARNING:OwlSchemaGenerator:Unrecognized prefix: rdf
WARNING:OwlSchemaGenerator:Unrecognized prefix: rdfs
WARNING:OwlSchemaGenerator:Unrecognized prefix: skos
WARNING:OwlSchemaGenerator:Unrecognized prefix: MIxS
WARNING:root:	Slot "has output" owner (omics processing) does not match workflow execution activity
WARNING:root:	Slot "has input" owner (biosample processing) does not match workflow execution activity
WARNING:root:	Slot "ecosystem_category" owner (study) does not match biosample
WARNING:root:	Slot "ecosystem" owner (study) does not match biosample
WARNING:root:	Slot "ecosystem_type" owner (study) does not match biosample
WARNING:root:	Slot "specific_ecosystem" owner (study) does not match biosample
WARNING:root:	Slot "ecosystem_subtype" owner (study) does not match biosample
WARNING:root:	Slot "was informed by" owner (agent) does not match activity
Traceback (most recent call last):
  File "/Users/wdduncan/opt/anaconda3/bin/gen-owl", line 8, in <module>
    sys.exit(cli())
  File "/Users/wdduncan/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wdduncan/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/wdduncan/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wdduncan/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/wdduncan/.local/lib/python3.7/site-packages/biolinkml/generators/owlgen.py", line 271, in cli
    print(OwlSchemaGenerator(yamlfile, **kwargs).serialize(**kwargs))
  File "/Users/wdduncan/.local/lib/python3.7/site-packages/biolinkml/generators/owlgen.py", line 37, in __init__
    self.metamodel.resolve()
  File "/Users/wdduncan/.local/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 121, in resolve
    self.raise_value_error(f'Class "{cls.name}" - unknown slot: "{slotname}"', slotname)
  File "/Users/wdduncan/.local/lib/python3.7/site-packages/biolinkml/utils/schemaloader.py", line 494, in raise_value_error
    raise ValueError(f'{"" if loc_str is None or not getattr(loc_str, "loc") else (loc_str.loc() + " ")} {error}')
  File "/Users/wdduncan/.local/lib/python3.7/site-packages/biolinkml/utils/yamlutils.py", line 111, in loc
    return f"{self._s.name}: line {self._s.line + 1} col {self._s.column + 1}"
AttributeError: 'NoneType' object has no attribute 'name'
```
cc @deepakunni3 @cmungall

**Comment by wdduncan** [comment]
This is now fixed.
